### ISSUE TITLE
duplicate @nestjs/common declaration

### ISSUE THREAD

**Issue by eddiejaoude** [Cahllagerfeld/nestjs-astra-module#22]
```
"@nestjs/common": "^7.6.15",
```

Appears twice in `package.json`

**Comment by Cahllagerfeld** [comment]
I'm not quite sure about that.
One is a `devDependency` and the other one is for `peerDependency`.
I used [this](https://github.com/nestjs/config/blob/master/package.json) as a reference where they are also set as `dev-` and `peerDependency`

**Comment by eddiejaoude** [comment]
Ah yes it is peer dependency, my mistake. I will close.
