### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by eddiejaoude** [Cahllagerfeld/nestjs-astra-module#4]
- what is the project for
- quickstart
...

**Comment by Cahllagerfeld** [comment]
I was aware of these things :D I just wanted to get this up and running as fast as possible and add the readme when the module is ready to use.. 😅

**Comment by eddiejaoude** [comment]
Sure, I am just making notes so I don't forget 🤓

**Comment by Cahllagerfeld** [comment]
Thank you !! :D

**Comment by RICK-FLORES** [comment]
I can create the file to get it started if that okay. Not entirely sure what the project entails but I'd like to contribute.

**Comment by Cahllagerfeld** [comment]
> 
> 
> I can create the file to get it started if that okay. Not entirely sure what the project entails but I'd like to contribute.

Sure 😄 Currently theres no, so you add much value by creating it!

**Comment by Cahllagerfeld** [comment]
Readme Added with PR #10
