### ISSUE TITLE
Use env to avoid committing any private tokens

### ISSUE THREAD

**Issue by eddiejaoude** [Cahllagerfeld/nestjs-astra-module#5]

**Comment by Cahllagerfeld** [comment]
I thought about this already. I could make the config-Module a peer-dependency and define the name of the Environment-variables here. 
Then I had to thought, that this actually should be configured by the main-App not my module. Thats why I want to implement a `forRootAsync` Method. By doing this the developer can use his own env-variable or hardcode it or whatever he wants.
What do you think about that?

**Comment by eddiejaoude** [comment]
oh yes, good idea! You are right 🤓 . The main app should take care of this and pass it through 👍

**Comment by Cahllagerfeld** [comment]
This got implemented with the forRootAsync-Method
