### ISSUE TITLE
Stricter types / Generic types

### ISSUE THREAD

**Issue by eddiejaoude** [Cahllagerfeld/nestjs-astra-module#6]
Might require some investigation into AstraJS Collections, but being able to go from this...
```ts
public get(id: string): Observable<any> {
    const response = this.collection.get(id);
    return from(response);
}
```

to this, would be awesome... (might need some type casting)

```ts
public get<T>(id: string): Observable<T> {
    const response = this.collection.get(id);
    return from(response);
}
```

**Comment by Cahllagerfeld** [comment]
I'm having local changes here, where I did some refactoring for the `astra`-Service. But you're right we probably have to take a look at the astrapackage again to specify the different interfaces
